#!/bin/sh
STEP_INIT_NAME="${STEP_INIT_NAME:-local.site}"
function __root () {
    rm -f "${STEP_ROOT}" \
    & printf "%s\n" "${STEP_ROOT} removed"
    rm -f "${SITECRT}" "${SITEKEY}" \
    & printf "%s\n%s\n" "${SITECRT} removed" "${SITEKEY} removed"
    step ca root "${STEP_ROOT}"
}
function __token () {
    local map="local test"
    if [ -n ${STEP_INIT_MAP} ]; then
        map="${map} ${STEP_INIT_MAP}"
    fi
    set -- \
    "${STEP_INIT_NAME}" \
    --san localhost
    if [ -n "${STEP_INIT_DNS}" ]; then
        for domain in $STEP_INIT_DNS; do
            for val in $map; do
                set -- ${@} \
                --san "${domain}.${val}" \
                --san "*.${domain}.${val}"
            done
        done
    fi
    unset domain
    if [ -n "${STEP_INIT_SAN}" ]; then
        for san in $STEP_INIT_SAN; do
            set -- ${@} \
            --san "${san}"
        done
    fi
    unset san
    step ca token ${@}
}
function __certificate () {
    TOKEN=$1
    shift 1
    if [ -n "${TOKEN}" ]; then
        set -- \
        --token "${TOKEN}" \
        "${STEP_INIT_NAME}" \
        "${SITECRT}" \
        "${SITEKEY}"
        step ca certificate ${@}
    fi
}
function __init () {
    __root
    __certificate $(__token)
}
__init
exec "${@}"