networks:
    backend:
        driver: bridge
    redis:
        driver: bridge
    step:
        driver: bridge
    www:
        driver: bridge
volumes:
    mysql:
        driver: local
    redis:
        driver: local
    smallstep:
        driver: local
secrets:
    password:
        file: ./ssl/secrets/password
    provisioner_password:
        file: ./ssl/secrets/provisioner_password
services:
    step:
        image: smallstep/step-ca:latest
        environment:
            STEPPATH: /home/step
            DOCKER_STEPCA_INIT_NAME: Proxy Murder - Smallstep C.A.
            DOCKER_STEPCA_INIT_DNS_NAMES: step
            DOCKER_STEPCA_INIT_ADDRESS: :5739
        volumes:
            - ./ssl:/home/step
        networks:
            - step
    smallstep:
        image: proxymurder/smallstep:latest
        environment:
            STEP_INIT_DNS: default
            STEP_CA_URL: https://step:5739
            STEP_FINGERPRINT: 2fc1579032a34e6a37a3eb46c9cb3b90e5db632d966b81480332cffc433100c7
            STEP_KID: o3b64QSjlXdHwBt3RYtUgZPgH_t35AmNLMTqRg_KDE8
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_PROVISIONER_PASSWORD_FILE: /run/secrets/provisioner_password
            STEP_ROOT: /var/local/step/root_ca.crt
        volumes:
            - smallstep:/var/local/step
        secrets:
            - password
            - provisioner_password
        networks:
            - step
        depends_on:
            - step
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: default
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    redis:
        image: redis:alpine
        volumes:
            - redis:/data
        networks:
            - redis
        ports:
            - 6379
    php:
        image: proxymurder/php:latest
        volumes:
            - ./laravel/src:/var/www/html
        networks:
            - backend
            - redis
        ports:
            - 9000
        depends_on:
            - mysql
            - redis
    wss:
        image: proxymurder/node:ws
        environment:
            WS_STEPPATH: /var/local/step
            REDIS_HOST: redis
        volumes:
            - smallstep:/var/local/step:ro
            - ./ws/app:/var/www/websockets
        networks:
            - redis
            - www
        ports:
            - 5555
        depends_on:
            - smallstep
            - redis
    laravel:
        image: proxymurder/vite:latest
        environment:
            VITE_STEPPATH: /var/local/step
            VITE_HMR_HOST: default.test
            VITE_HMR_CLIENTPORT: 443
        volumes:
            - smallstep:/var/local/step:ro
            - ./laravel/src:/var/www/html
        networks:
            - backend
            - www
        ports:
            - 5173
        depends_on:
            - smallstep
            - php
    app:
        image: proxymurder/vite:latest
        environment:
            VITE_STEPPATH: /var/local/step
            VITE_BASE_URL: app.default.local
            VITE_BACKEND_URL: default.local
            VITE_WS_URL: ws.default.local
            VITE_OAUTH_CLIENT: 
            VITE_TEST_OAUTH_CLIENT: 
        volumes:
            - smallstep:/var/local/step:ro
            - ./vite/app:/var/www/html
        networks:
            - www
        ports:
            - 5173
        depends_on:
            - smallstep
            - php
    backend:
        image: proxymurder/camarero:latest
        environment:
            SERVER_YAML: /etc/nginx/yaml/default.php.yaml
            SERVER_WATCH_CRT: /var/local/step/site.crt
        volumes:
            - smallstep:/var/local/step:ro
            - ./laravel/src:/var/www/html
        networks:
            - backend
            - www
        ports:
            - 6000
        depends_on:
            - smallstep
            - php
    frontend:
        image: proxymurder/camarero:latest
        environment:
            SERVER_YAML: /etc/nginx/yaml/default.js.yaml
            SERVER_WATCH_CRT: /var/local/step/site.crt
        volumes:
            - smallstep:/var/local/step:ro
            - ./vue/app:/var/www/html
        networks:
            - www
        ports:
            - 3000
        depends_on:
            - smallstep
            - php
    www:
        image: proxymurder/camarero:latest
        environment:
            SERVER_YAML: /etc/nginx/yaml/proxy.yaml
            SERVER_WATCH_CRT: /var/local/step         
        volumes:
            - smallstep:/var/local/step:ro
            - ./proxy.yaml:/etc/nginx/yaml/proxy.yaml
        networks:
            - www
        ports:
            - 80:80
            - 443:443
        depends_on:
            - smallstep
            - laravel
            - app
            - backend
            - frontend
            - wss
