networks:
    backend:
        name: ${APP_NAME}-backend-network
        driver: bridge
    dev:
        name: ${APP_NAME}-dev-network
        driver: bridge
    local:
        name: ${APP_NAME}-local-network
        driver: bridge
    redis:
        name: ${APP_NAME}-redis-network
        driver: bridge
    step:
        name: ${APP_NAME}-step-network
        driver: bridge
volumes:
    step:
        name: ${APP_NAME}-step-volume
        driver: local
    mysql:
        name: ${APP_NAME}-mysql-volume
        driver: local
    redis:
        name: ${APP_NAME}-redis-volume
        driver: local
secrets:
    password:
        file: ./step/certauth/secrets/password
services:
    certauth:
        image: smallstep/step-ca
        volumes:
            - ./step/certauth:/home/step
        networks:
            - step
        ports:
            - 5739
    certwatch:
        build:
            context: ./step/certwatch
        image: proxymurder/step-cli
        environment:
            COMMON_NAME: ${CERTS_NAME}
            DOMAINS: ${CERTS_DOMAINS}
            STEPPATH: ${CERTS_PATH}
            STEP_CA_URL: ${CERTS_URL}
            STEP_FINGERPRINT: ${CERTS_FINGERPRINT}
            STEP_KID: ${CERTS_KID}
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_ROOT: /home/step/root_ca.crt
        volumes:
            - step:/home/step
            - ./step/tmp:/var/local/step
        secrets:
            - password
        networks:
            - step
        depends_on:
            - certauth
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    memory:
        image: redis:alpine
        volumes:
            - redis:/data
        networks:
            - redis
        ports:
            - 6379
    php:
        build:
            context: ./php
        image: proxymurder/php
        volumes:
            - ./php/backend:/var/www/html
        networks:
            - backend
            - redis
        ports:
            - 9000
        depends_on:
            - db
            - memory
    laravel:
        build:
            context: ./node
        image: proxymurder/node
        environment:
            - VITE_SERVER_HMR=${DEV_SERVER_LARAVEL_HMR}
            - VITE_SERVER_KEY=${DEV_SERVER_KEY}
            - VITE_SERVER_CERT=${DEV_SERVER_CERT}
            - VITE_SERVER_CERTPATH=../../..${CERTS_PATH}
        working_dir: /var/www/html
        volumes:
            - step:/home/step:ro
            - ./php/backend:/var/www/html
        command: ['npm', 'run', 'dev']
        networks:
            - dev
        ports:
            - 5173
        depends_on:
            - certwatch
            - php
    php-www:
        build:
            context: ./nginx
        image: proxymurder/nginx
        volumes:
            - step:/home/step:ro
            - ./php/backend:/var/www/html
            - ./nginx/conf.d/php:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
        networks:
            - backend
            - dev
            - local
        ports:
            - 443
        depends_on:
            - certwatch
            - php
    app:
        build:
            context: ./node
        image: proxymurder/node
        environment:
            - VITE_SERVER_KEY=${DEV_SERVER_KEY}
            - VITE_SERVER_CERT=${DEV_SERVER_CERT}
            - VITE_SERVER_CERTPATH=../../..${CERTS_PATH}
        working_dir: /usr/share/nginx/html
        volumes:
            - step:/home/step:ro
            - ./node/app:/usr/share/nginx/html
        command: ['npm', 'run', 'dev']
        networks:
            - dev
        ports:
            - 5173
        depends_on:
            - certwatch
            - php
    app-www:
        build:
            context: ./nginx
        image: proxymurder/nginx
        volumes:
            - step:/home/step:ro
            - ./node/app:/usr/share/nginx/html
            - ./nginx/conf.d/node:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
        networks:
            - local
            - dev
        ports:
            - 443
        depends_on:
            - certwatch
            - php
    sockjs:
        build:
            context: ./node
        image: proxymurder/node
        environment:
            - WS_SERVER_KEY=${DEV_SERVER_KEY}
            - WS_SERVER_CERT=${DEV_SERVER_CERT}
            - REDIS_URL=memory:6379
        working_dir: /sockjs
        volumes:
            - step:/home/step:ro
            - ./node/sockjs:/sockjs
        command: ['node', 'server.js']
        networks:
            - redis
            - dev
            - local
        ports:
            - 5555
        depends_on:
            - certwatch
            - memory
    dev:
        build:
            context: ./nginx
        image: proxymurder/nginx
        volumes:
            - step:/home/step:ro
            - ./nginx/conf.d/proxy/dev:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
            - ./nginx/extra/proxy.conf:/etc/nginx/extra/proxy.conf
        networks:
            - dev
        ports:
            - 80:80
            - 443:443
        depends_on:
            - certwatch
            - laravel
            - php-www
            - app
            - app-www
            - sockjs
    www:
        build:
            context: ./nginx
        image: proxymurder/nginx
        volumes:
            - step:/home/step:ro
            - ./nginx/conf.d/proxy/prod:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
            - ./nginx/extra/proxy.conf:/etc/nginx/extra/proxy.conf
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - certwatch
            - php-www
            - app-www
            - sockjs
