networks:
    backend:
        name: ${APP_NAME}-backend
        driver: bridge
    local:
        name: ${APP_NAME}-local
        driver: bridge
    step:
        name: ${APP_NAME}-step
        driver: bridge
volumes:
    step:
        name: ${APP_NAME}-step-volume
        driver: local
    mysql:
        name: ${APP_NAME}-mysql-volume
        driver: local
secrets:
    password:
        file: ./step/ca/secrets/password
services:
    ca:
        image: smallstep/step-ca
        volumes:
            - ./step/ca:/home/step
        networks:
            - step
        ports:
            - 443
    certwatch:
        build:
            context: ./step/watch
        image: ${APP_NAME}/step-cli
        environment:
            COMMON_NAME: ${CERTWATCH_NAME}
            DOMAINS: ${CERTWATCH_DOMAINS}
            STEPPATH: ${CERTWATCH_PATH}
            STEP_CA_URL: ${CERTWATCH_URL}
            STEP_FINGERPRINT: ${CERTWATCH_FINGERPRINT}
            STEP_KID: ${CERTWATCH_KID}
            STEP_PASSWORD_FILE: ${CERTWATCH_PASSWORD_FILE}
            STEP_ROOT: ${CERTWATCH_ROOT}
        volumes:
            - step:/home/step
            - ./step/tmp:/var/local/step
        secrets:
            - password
        networks:
            - step
        depends_on:
            - ca
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    php:
        build:
            context: ./php
        image: ${APP_NAME}/php
        volumes:
            - ./php/backend:/var/www/html
        networks:
            - backend
        ports:
            - 9000
        depends_on:
            - db
    vite-backend:
        build:
            context: ./node
        image: ${APP_NAME}/node
        working_dir: /var/www/html
        volumes:
            - step:/home/step:ro
            - ./php/backend:/var/www/html
        command: ['npm', 'run', 'dev']
        networks:
            - local
        ports:
            - 443
        depends_on:
            - certwatch
    backend:
        build:
            context: ./nginx
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./php/backend:/var/www/html
            - ./nginx/conf.d/php:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
        networks:
            - backend
            - local
        ports:
            - 443
        depends_on:
            - certwatch
            - php
    vite:
        build:
            context: ./node
        image: ${APP_NAME}/node
        working_dir: /usr/share/nginx/html
        volumes:
            - step:/home/step:ro
            - ./node/app:/usr/share/nginx/html
        command: ['npm', 'run', 'dev']
        networks:
            - local
        ports:
            - 443
        depends_on:
            - certwatch
    app:
        build:
            context: ./nginx
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./node/app:/usr/share/nginx/html
            - ./nginx/conf.d/node:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
        networks:
            - local
        ports:
            - 443
        depends_on:
            - certwatch
    dev:
        build:
            context: ./nginx
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./nginx/conf.d/proxy/dev:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
            - ./nginx/extra/proxy.conf:/etc/nginx/extra/proxy.conf
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
            - certwatch
            - backend
            - vite
            - vite-backend
    prod:
        build:
            context: ./nginx
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./nginx/conf.d/proxy/prod:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
            - ./nginx/extra/proxy.conf:/etc/nginx/extra/proxy.conf
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
            - certwatch
            - backend
