networks:
    api-network:
        driver: bridge
    local-network:
        driver: bridge
    main-network:
        driver: bridge
    step-network:
        driver: bridge
volumes:
    step:
        driver: local
    mysql:
        driver: local
secrets:
    password:
        file: ./step/ca/secrets/password
services:
    db:
        image: mysql:latest
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: reverse_proxy
        ports:
            - 3306
        networks:
            - api-network
    php:
        build:
            context: ./api/src
        volumes:
            - ./api/src:/var/www/html
        ports:
            - 9000
        depends_on:
            - db
        networks:
            - api-network
    api:
        image: node:alpine
        user: node
        volumes:
            - ./api/src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        command: ['run', 'watch']
        networks:
            - api-network
    api-www:
        image: nginx:alpine
        volumes:
            - ./api/src:/var/www/html
            - ./api/nginx/conf.d:/etc/nginx/conf.d
            - ./api/nginx/proxy.conf:/etc/nginx/proxy.conf
        ports:
            - 80
        depends_on:
            - db
            - php
        networks:
            - local-network
            - api-network
    main:
        image: node:alpine
        working_dir: /usr/share/nginx/html
        volumes:
            - ./main/app:/usr/share/nginx/html
        entrypoint: ['npm']
        command: ['run', 'watch']
        networks:
            - main-network
    main-www:
        image: nginx:alpine
        volumes:
            - ./main/app:/usr/share/nginx/html
            - ./main/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80
        depends_on:
            - db
            - php
            - api-www
        networks:
            - local-network
            - main-network
    www:
        build:
            context: ./proxy
        volumes:
            - step:/home/step:ro
            - ./proxy/nginx/conf.d:/etc/nginx/conf.d
            - ./proxy/nginx/config:/etc/nginx/config
        depends_on:
            - api-www
            - main-www
            - step-certs
        networks:
            - local-network
        ports:
            - 80:80
            - 443:443
    step-ca:
        image: smallstep/step-ca
        volumes:
            - ./step/ca:/home/step
        ports:
            - 443
        networks:
            - step-network
    step-certs:
        build:
            context: ./step/certs
        volumes:
            - step:/home/step
            - ./step/certs/tmp:/var/local/step
        secrets:
            - password
        environment:
            STEPPATH: /home/step
            STEP_CA_URL: https://step-ca
            STEP_FINGERPRINT: 473fd13142b2bf3edb96f533052b8ec013af91d74403e5d89ef2d99385e44154
            STEP_ROOT: /home/step/root_ca.crt
            STEP_KID: mbpaw9iGNw81raKt7Ph06Kk2aShmSi0RKuxSeQItNEw
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_NAME: e-stubb.local
        depends_on:
            - step-ca
        networks:
            - step-network
