networks:
    step:
        driver: bridge
    redis:
        driver: bridge
    backend:
        driver: bridge
    local:
        driver: bridge
    www:
        driver: bridge
volumes:
    mysql:
        driver: local
    redis:
        driver: local
    step:
        driver: local
secrets:
    password:
        file: ./step/certificates/tmp/password
services:
    certificates:
        image: test/certificates:latest
        environment:
            STEPPATH: /home/step
            STEPCA_INIT_NAME: Development
            STEPCA_INIT_DNS: certificates
        volumes:
            - ./step/certificates/tmp:/home/step
        networks:
            - step
        ports:
            - 5739
    renewer:
        image: test/renewer:latest
        environment:
            STEP_INIT_DNS: default proxyd
            STEP_CA_URL: https://certificates:5739
            STEP_FINGERPRINT: 55953348a481cb7acd0d9adc9c4dfdc5e2086955a6ac0772a78f67c3f9121647
            STEP_KID: CcOa-V98ehJwsf_M7Rrujefuzn__Uf5_S-3Dni1IndU
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_ROOT: /var/local/step/root_ca.crt
        volumes:
            - step:/var/local/step
        secrets:
            - password
        networks:
            - step
        depends_on:
            - certificates
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: default
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    memory:
        image: redis:alpine
        volumes:
            - redis:/data
        networks:
            - redis
        ports:
            - 6379
    php:
        image: test/laravel:latest
        volumes:
            - ./laravel/src:/var/www/html
        networks:
            - backend
            - redis
        ports:
            - 9000
        depends_on:
            - db
            - memory
    nphp:
        image: test/nphp:latest
        environment:
            VITE_STEPPATH: /var/local/step
            VITE_HMR_HOST: default.test
            VITE_HMR_CLIENTPORT: 443
        volumes:
            - step:/var/local/step:ro
            - ./laravel/src:/var/www/html
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - renewer
            - php
    backend:
        image: test/nginx:latest
        volumes:
            - step:/var/local/step:ro
            - ./laravel/src:/var/www/html
            - ./nginx/backend:/etc/nginx/conf.d
        networks:
            - backend
            - local
            - www
        ports:
            - 6000
        depends_on:
            - renewer
            - php
    app:
        image: test/vue:latest
        environment:
            VITE_STEPPATH: /var/local/step
            VITE_BASE_URL: app.default.local
            VITE_BACKEND_URL: default.local
            VITE_WS_URL: ws.default.local
            VITE_OAUTH_CLIENT: 
            VITE_TEST_OAUTH_CLIENT: 
        volumes:
            - step:/var/local/step:ro
            - ./vue/app:/var/www/html
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - renewer
            - php
    frontend:
        image: test/nginx:latest
        volumes:
            - step:/var/local/step:ro
            - ./vue/app:/var/www/html
            - ./nginx/frontend:/etc/nginx/conf.d
        networks:
            - local
            - www
        ports:
            - 3000
        depends_on:
            - renewer
            - php
    ws:
        image: test/websockets:latest
        environment:
            WS_STEPPATH: /var/local/step
            REDIS_HOST: memory
        volumes:
            - step:/var/local/step:ro
            - ./websockets/ws:/var/www/websockets
        networks:
            - redis
            - local
            - www
        ports:
            - 5000
        depends_on:
            - renewer
            - memory
    local:
        image: test/nginx:latest
        volumes:
            - step:/var/local/step:ro
            - ./nginx/local:/etc/nginx/conf.d
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - renewer
            - nphp
            - backend
            - app
            - frontend
            - ws
    www:
        image: test/nginx:latest
        volumes:
            - step:/var/local/step:ro
            - ./nginx/www:/etc/nginx/conf.d
        networks:
            - www
        ports:
            - 80:80
            - 443:443
        depends_on:
            - renewer
            - backend
            - frontend
            - ws
