networks:
    api-network:
        name: ${APP_NAME}/api-network
        driver: bridge
    local-network:
        name: ${APP_NAME}/local-network
        driver: bridge
    main-network:
        name: ${APP_NAME}/main-network
        driver: bridge
    step-network:
        name: ${APP_NAME}/step-network
        driver: bridge
volumes:
    step:
        name: ${APP_NAME}-step-volume
        driver: local
    mysql:
        name: ${APP_NAME}-mysql-volume
        driver: local
secrets:
    password:
        file: ./step/ca/secrets/password
services:
    step-ca:
        image: smallstep/step-ca
        volumes:
            - ./step/ca:/home/step
        networks:
            - step-network
        ports:
            - 443
    step-watch:
        build:
            context: ./step/watch
        image: ${APP_NAME}/step-cli
        environment:
            COMMON_NAME: ${STEP_WATCH_NAME}
            DOMAINS: ${STEP_WATCH_DOMAINS}
            STEPPATH: /home/step
            STEP_CA_URL: https://step-ca
            STEP_FINGERPRINT: ${STEP_WATCH_FINGERPRINT}
            STEP_KID: ${STEP_WATCH_KID}
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_ROOT: /home/step/root_ca.crt
        volumes:
            - step:/home/step
            - ./step/tmp:/var/local/step
        secrets:
            - password
        networks:
            - step-network
        depends_on:
            - step-ca
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - api-network
        ports:
            - 3306
        depends_on:
            - step-watch
    php:
        build:
            context: ./php
        image: ${APP_NAME}/php
        volumes:
            - ./php/api:/var/www/html
        networks:
            - api-network
        ports:
            - 9000
        depends_on:
            - db
    www-api:
        build:
            context: ./www
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./php/api:/var/www/html
            - ./www/nginx/conf.d/api:/etc/nginx/conf.d
        networks:
            - api-network
            - local-network
        ports:
            - 80
        depends_on:
            - php
    www-main:
        build:
            context: ./www
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./node/main:/usr/share/nginx/html
            - ./www/nginx/conf.d/main:/etc/nginx/conf.d
        networks:
            - main-network
            - local-network
        ports:
            - 80
        depends_on:
            - www-api
    api:
        build:
            context: ./node
        image: ${APP_NAME}/node
        user: node
        working_dir: /var/www/html
        volumes:
            - ./php/api:/var/www/html
        command: ['npm', 'run', 'dev']
        networks:
            - api-network
            - local-network
        ports:
            - 80
        depends_on:
            - www-api
    main:
        build:
            context: ./node
        image: ${APP_NAME}/node
        user: node
        working_dir: /usr/share/nginx/html
        volumes:
            - ./node/main:/usr/share/nginx/html
        command: ['npm', 'run', 'dev']
        networks:
            - main-network
            - local-network
        ports:
            - 80
        depends_on:
            - www-api
    dev:
        build:
            context: ./www
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./www/nginx/conf.d/proxy/dev:/etc/nginx/conf.d
            - ./www/nginx/https.conf:/etc/nginx/https.conf
            - ./www/nginx/proxy-v2.conf:/etc/nginx/proxy-v2.conf
        networks:
            - local-network
        ports:
            - 80:80
            - 443:443
        depends_on:
            - api
            - main
            - www-main
