version: '3.9'
networks:
  local_network:
    driver: bridge
  api_network:
    driver: bridge
  main_network:
    driver: bridge
volumes:
  mysql:
    driver: local
services:
  db:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: reverse_proxy
    ports:
      - 3306
    networks:
      - api_network
  php:
    build:
      context: ./api/src
    volumes:
      - ./api/src:/var/www/html
    ports:
      - 9000
    depends_on:
      - db
    networks:
      - api_network
  api_www:
    image: nginx:latest
    volumes:
      - ./api/src:/var/www/html
      - ./api/nginx/conf.d:/etc/nginx/conf.d
      - ./api/nginx/proxy.conf:/etc/nginx/proxy.conf
    ports:
      - 80
    depends_on:
      - db
      - php
    networks:
      - local_network
      - api_network
  npm:
    image: node:alpine
    user: node
    volumes:
      - ./api/src:/var/www/html
    depends_on:
      - db
      - php
      - api_www
    working_dir: /var/www/html
    entrypoint: ['npm']
    command: ['run', 'watch']
    networks:
      - api_network
  main:
    image: node:alpine
    working_dir: /usr/share/nginx/html
    volumes:
      - ./main/app:/usr/share/nginx/html
    depends_on:
      - main_www
    command: ['npm', 'run', 'watch']
    networks:
      - main_network
  main_www:
    image: nginx:latest
    volumes:
      - ./main/app:/usr/share/nginx/html
      - ./main/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80
    depends_on:
      - db
      - php
      - api_www
    networks:
      - local_network
      - main_network
  www:
    image: nginx:latest
    volumes:
      - ./proxy/ssl/certs:/etc/ssl/certs/nginx
      - ./proxy/nginx/conf.d:/etc/nginx/conf.d
      - ./proxy/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./proxy/nginx/ssl.conf:/etc/nginx/ssl.conf
    depends_on:
      - db
      - php
      - api_www
      - main_www
    networks:
      - local_network
    ports:
      - 80:80
      - 443:443
