networks:
    backend:
        driver: bridge
    local:
        driver: bridge
    redis:
        driver: bridge
    step:
        driver: bridge
    www:
        driver: bridge
volumes:
    mysql:
        driver: local
    redis:
        driver: local
    step:
        driver: local
secrets:
    password:
        file: ./step/certificates/tmp/password
services:
    certificates:
        image: test/certificates:latest
        environment:
            STEPCA_INIT_NAME: Development
            STEPCA_INIT_DNS: certificates
        volumes:
            - ./step/certificates/tmp:/home/step/certificates
        networks:
            - step
        ports:
            - 5739
    renewer:
        image: test/renewer:latest
        environment:
            STEP_INIT_DNS: default proxyd
            STEP_CA_URL: https://certificates:5739
            STEP_FINGERPRINT: 673faa2736cfab929271386853878ad0a7413ec52bdbaceebb6fddfc8de67212
            STEP_KID: HrjM7KHlS6O2N-42XuXvvFSu86w18SODvlux4SGfKKg
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_ROOT: /home/step/renewer/root_ca.crt
        volumes:
            - step:/home/step/renewer
        secrets:
            - password
        networks:
            - step
        depends_on:
            - certificates
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: default
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    memory:
        image: redis:alpine
        volumes:
            - redis:/data
        networks:
            - redis
        ports:
            - 6379
    php:
        image: test/php:latest
        volumes:
            - ./php/src:/home/php/src
        networks:
            - backend
            - redis
        ports:
            - 9000
        depends_on:
            - db
            - memory
    nphp:
        image: test/nphp:latest
        environment:
            VITE_STEPPATH: /home/step/renewer
            VITE_HMR_HOST: default.test
            VITE_HMR_CLIENTPORT: 443
        volumes:
            - step:/home/step/renewer:ro
            - ./php/src:/home/node/src
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - renewer
            - php
    backend:
        image: test/nginx:latest
        volumes:
            - step:/home/step/renewer:ro
            - ./php/src:/home/php/src
            - ./nginx/backend:/etc/nginx/conf.d
        networks:
            - backend
            - local
            - www
        ports:
            - 6000
        depends_on:
            - renewer
            - php
    app:
        image: test/vue:latest
        environment:
            VITE_STEPPATH: /home/step/renewer
            VITE_BASE_URL: app.default.local
            VITE_BACKEND_URL: default.local
            VITE_WS_URL: ws.default.local
            VITE_OAUTH_CLIENT: 
            VITE_TEST_OAUTH_CLIENT: 
        volumes:
            - step:/home/step/renewer:ro
            - ./node/vue/app:/home/node/app
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - renewer
            - php
    frontend:
        image: test/nginx:latest
        volumes:
            - step:/home/step/renewer:ro
            - ./node/vue/app:/home/node/app
            - ./nginx/frontend:/etc/nginx/conf.d
        networks:
            - local
            - www
        ports:
            - 3000
        depends_on:
            - renewer
            - php
    ws:
        image: test/websockets:latest
        environment:
            WS_STEPPATH: /home/step/renewer
            REDIS_HOST: memory
        volumes:
            - step:/home/step/renewer:ro
            - ./node/websockets/ws:/home/node/ws
        networks:
            - redis
            - local
            - www
        ports:
            - 5000
        depends_on:
            - renewer
            - memory
    local:
        image: test/nginx:latest
        volumes:
            - step:/home/step/renewer:ro
            - ./nginx/local:/etc/nginx/conf.d
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - renewer
            - nphp
            - backend
            - app
            - frontend
            - ws
    www:
        image: test/nginx:latest
        volumes:
            - step:/home/step/renewer:ro
            - ./nginx/www:/etc/nginx/conf.d
        networks:
            - www
        ports:
            - 80:80
            - 443:443
        depends_on:
            - renewer
            - backend
            - frontend
            - ws
