networks:
    backend:
        name: ${APP_NAME}-backend-network
        driver: bridge
    dev:
        name: ${APP_NAME}-dev-network
        driver: bridge
    local:
        name: ${APP_NAME}-local-network
        driver: bridge
    redis:
        name: ${APP_NAME}-redis-network
        driver: bridge
    step:
        name: ${APP_NAME}-step-network
        driver: bridge
volumes:
    step:
        name: ${APP_NAME}-step-volume
        driver: local
    mysql:
        name: ${APP_NAME}-mysql-volume
        driver: local
    redis:
        name: ${APP_NAME}-redis-volume
        driver: local
secrets:
    password:
        file: ./step/ca/secrets/password
services:
    ca:
        image: smallstep/step-ca
        volumes:
            - ./step/ca:/home/step
        networks:
            - step
        ports:
            - 443
    certwatch:
        build:
            context: ./step/watch
        image: ${APP_NAME}/step-cli
        environment:
            COMMON_NAME: ${CERTWATCH_NAME}
            DOMAINS: ${CERTWATCH_DOMAINS}
            STEPPATH: ${CERTWATCH_PATH}
            STEP_CA_URL: ${CERTWATCH_URL}
            STEP_FINGERPRINT: ${CERTWATCH_FINGERPRINT}
            STEP_KID: ${CERTWATCH_KID}
            STEP_PASSWORD_FILE: ${CERTWATCH_PASSWORD_FILE}
            STEP_ROOT: ${CERTWATCH_ROOT}
        volumes:
            - step:/home/step
            - ./step/tmp:/var/local/step
        secrets:
            - password
        networks:
            - step
        depends_on:
            - ca
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    memory:
        image: redis:alpine
        volumes:
            - redis:/data
        networks:
            - redis
        ports:
            - 6379
    php:
        build:
            context: ./php
        image: ${APP_NAME}/php
        volumes:
            - ./php/backend:/var/www/html
        networks:
            - backend
            - redis
        ports:
            - 9000
        depends_on:
            - db
            - memory
    laravel:
        build:
            context: ./node
        image: ${APP_NAME}/node
        environment:
            - VITE_SERVER_HMR=${DEV_SERVER_LARAVEL_HMR}
            - VITE_SERVER_KEY=${DEV_SERVER_KEY}
            - VITE_SERVER_CERT=${DEV_SERVER_CERT}
            - VITE_SERVER_CERTPATH=../../..${DEV_SERVER_CERT}
        working_dir: /var/www/html
        volumes:
            - step:/home/step:ro
            - ./php/backend:/var/www/html
        command: ['npm', 'run', 'dev']
        networks:
            - dev
        ports:
            - 443
        depends_on:
            - certwatch
            - php
    php-www:
        build:
            context: ./nginx
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./php/backend:/var/www/html
            - ./nginx/conf.d/php:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
        networks:
            - backend
            - dev
            - local
        ports:
            - 443
        depends_on:
            - certwatch
            - php
    app:
        build:
            context: ./node
        image: ${APP_NAME}/node
        environment:
            - VITE_SERVER_KEY=${DEV_SERVER_KEY}
            - VITE_SERVER_CERT=${DEV_SERVER_CERT}
            - VITE_SERVER_CERTPATH=../../../..${DEV_SERVER_CERT}
        working_dir: /usr/share/nginx/html
        volumes:
            - step:/home/step:ro
            - ./node/app:/usr/share/nginx/html
        command: ['npm', 'run', 'dev']
        networks:
            - dev
        ports:
            - 443
        depends_on:
            - certwatch
            - php
    websocket:
        build:
            context: ./node
        image: ${APP_NAME}/node
        working_dir: /websocket
        volumes:
            - step:/home/step:ro
            - ./node/websocket:/websocket
        command: ['node', 'socket.js']
        networks:
            - redis
            - dev
            - local
        ports:
            - 80
        depends_on:
            - certwatch
            - memory
    app-www:
        build:
            context: ./nginx
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./node/app:/usr/share/nginx/html
            - ./nginx/conf.d/node:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
        networks:
            - local
            - dev
        ports:
            - 443
        depends_on:
            - certwatch
            - php
    dev:
        build:
            context: ./nginx
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./nginx/conf.d/proxy/dev:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
            - ./nginx/extra/proxy.conf:/etc/nginx/extra/proxy.conf
        networks:
            - dev
        ports:
            - 80:80
            - 443:443
        depends_on:
            - certwatch
            - laravel
            - php-www
            - app
            - app-www
            - websocket
    www:
        build:
            context: ./nginx
        image: ${APP_NAME}/nginx
        volumes:
            - step:/home/step:ro
            - ./nginx/conf.d/proxy/prod:/etc/nginx/conf.d
            - ./nginx/extra/https.conf:/etc/nginx/extra/https.conf
            - ./nginx/extra/proxy.conf:/etc/nginx/extra/proxy.conf
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - certwatch
            - php-www
            - app-www
            - websocket
