networks:
    step:
        driver: bridge
    redis:
        driver: bridge
    backend:
        driver: bridge
    local:
        driver: bridge
    www:
        driver: bridge
volumes:
    mysql:
        driver: local
    redis:
        driver: local
    step:
        driver: local
secrets:
    password:
        file: ./ssl/secrets/password
    provisioner_password:
        file: ./ssl/secrets/provisioner_password
services:
    certificates:
        image: smallstep/step-ca:latest
        environment:
            STEPPATH: /home/step
            DOCKER_STEPCA_INIT_NAME: ProxydTest
            DOCKER_STEPCA_INIT_DNS_NAMES: certificates
            DOCKER_STEPCA_INIT_ADDRESS: :5739

        volumes:
            - ./ssl:/home/step
        networks:
            - step
        ports:
            - 5739
    renewer:
        image: proxymurder/step:renewer
        environment:
            STEP_INIT_DNS: default proxyd
            STEP_CA_URL: https://certificates:5739
            STEP_FINGERPRINT: 947ed4d6398ad372ff38427d7481f291d2f85ff03ddeba5ceed5871cbab76977
            STEP_KID: A8UgdWZta9dhlKKmj82CS6b8vgjJ8Ep_5kJ-aTYeP0k
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_PROVISIONER_PASSWORD_FILE: /run/secrets/provisioner_password
            STEP_ROOT: /var/local/step/root_ca.crt
        volumes:
            - step:/var/local/step
        secrets:
            - password
            - provisioner_password
        networks:
            - step
        depends_on:
            - certificates
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: default
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    memory:
        image: redis:alpine
        volumes:
            - redis:/data
        networks:
            - redis
        ports:
            - 6379
    php:
        image: proxymurder/php:laravel
        volumes:
            - ./laravel/src:/var/www/html
        networks:
            - backend
            - redis
        ports:
            - 9000
        depends_on:
            - db
            - memory
    nphp:
        image: proxymurder/node:laravel
        environment:
            VITE_STEPPATH: /var/local/step
            VITE_HMR_HOST: default.test
            VITE_HMR_CLIENTPORT: 443
        volumes:
            - step:/var/local/step:ro
            - ./laravel/src:/var/www/html
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - renewer
            - php
    backend:
        image: proxymurder/nginx:latest
        environment:
            NGCONF_PORT: 6000
            NGCONF_NAME: localhost
            NGCONF_SAN: '*.localhost'
            NGCONF_ROOT: /var/www/html/public
            NGCONF_LOG: /var/log/nginx
            # NGCONF_PHP: php:9000
            NGCONF_HTTPS: /var/local/step
            # NGCONF_OUT: /etc/nginx/conf.d/default.conf
            NGCONF_DEBUG: 0
        volumes:
            - step:/var/local/step:ro
            - ./laravel/src:/var/www/html
        networks:
            - backend
            - local
            - www
        ports:
            - 6000
        depends_on:
            - renewer
            - php
    app:
        image: proxymurder/vue:dev
        environment:
            VITE_STEPPATH: /var/local/step
            VITE_BASE_URL: app.default.local
            VITE_BACKEND_URL: default.local
            VITE_WS_URL: ws.default.local
            VITE_OAUTH_CLIENT: 
            VITE_TEST_OAUTH_CLIENT: 
        volumes:
            - step:/var/local/step:ro
            - ./vue/app:/var/www/html
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - renewer
            - php
    frontend:
        image: proxymurder/nginx:node
        volumes:
            - step:/var/local/step:ro
            - ./vue/app:/var/www/html
            - ./servers/frontend:/etc/nginx/conf.d
        networks:
            - local
            - www
        ports:
            - 3000
        depends_on:
            - renewer
            - php
    ws:
        image: proxymurder/node:ws
        environment:
            WS_STEPPATH: /var/local/step
            REDIS_HOST: memory
        volumes:
            - step:/var/local/step:ro
            - ./websockets/ws:/var/www/websockets
        networks:
            - redis
            - local
            - www
        ports:
            - 5000
        depends_on:
            - renewer
            - memory
    local:
        image: proxymurder/nginx:proxy
        volumes:
            - step:/var/local/step:ro
            - ./servers/local:/etc/nginx/conf.d
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - renewer
            - nphp
            - backend
            - app
            - frontend
            - ws
    www:
        image: proxymurder/nginx:proxy
        volumes:
            - step:/var/local/step:ro
            - ./servers/www:/etc/nginx/conf.d
        networks:
            - www
        ports:
            - 80:80
            - 443:443
        depends_on:
            - renewer
            - backend
            - frontend
            - ws
