networks:
    step:
        name: ${APP_NAME}-step-network
        driver: bridge
    redis:
        name: ${APP_NAME}-redis-network
        driver: bridge
    backend:
        name: ${APP_NAME}-backend-network
        driver: bridge
    local:
        name: ${APP_NAME}-local-network
        driver: bridge
    www:
        name: ${APP_NAME}-www-network
        driver: bridge
volumes:
    step:
        name: ${APP_NAME}-step-volume
        driver: local
    mysql:
        name: ${APP_NAME}-mysql-volume
        driver: local
    redis:
        name: ${APP_NAME}-redis-volume
        driver: local
secrets:
    password:
        file: ./step/certauth/secrets/password
services:
    certauth:
        image: smallstep/step-ca
        volumes:
            - ./step/certauth:/home/step
        networks:
            - step
        ports:
            - 5739
    certwatch:
        build:
            context: ./step/certwatch
        image: proxymurder/certwatch
        environment:
            COMMON_NAME: ${CERTS_NAME}
            DOMAINS: ${CERTS_DOMAINS}
            STEPPATH: ${CERTS_PATH}
            STEP_CA_URL: ${CERTS_URL}
            STEP_FINGERPRINT: ${CERTS_FINGERPRINT}
            STEP_KID: ${CERTS_KID}
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_ROOT: /home/step/root_ca.crt
        volumes:
            - step:/home/step
            - ./step/tmp:/var/local/step
        secrets:
            - password
        networks:
            - step
        depends_on:
            - certauth
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    memory:
        image: redis:alpine
        volumes:
            - redis:/data
        networks:
            - redis
        ports:
            - 6379
    php:
        build:
            context: ./laravel-backend
            dockerfile: php.Dockerfile
        image: proxymurder/php
        volumes:
            - ./laravel-backend:/backend
        networks:
            - backend
            - redis
        ports:
            - 9000
        depends_on:
            - db
            - memory
    ssr:
        build:
            context: ./laravel-backend
            dockerfile: node.Dockerfile
        image: proxymurder/ssr
        environment:
            - VITE_SERVER_HMR=${DEV_SERVER_LARAVEL_HMR}
            - VITE_SERVER_KEY=${DEV_SERVER_KEY}
            - VITE_SERVER_CERT=${DEV_SERVER_CERT}
            - VITE_SERVER_CERTPATH=../../..${CERTS_PATH}
        volumes:
            - step:/home/step:ro
            - ./laravel-backend:/backend
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - certwatch
            - php
    backend:
        build:
            context: ./nginx
        image: proxymurder/nginx
        volumes:
            - step:/home/step:ro
            - ./laravel-backend:/backend
            - ./nginx/backend:/etc/nginx/conf.d
        networks:
            - backend
            - local
            - www
        ports:
            - 6000
        depends_on:
            - certwatch
            - php
    app:
        build:
            context: ./vuejs-app
        image: proxymurder/app
        environment:
            - VITE_SERVER_KEY=${DEV_SERVER_KEY}
            - VITE_SERVER_CERT=${DEV_SERVER_CERT}
            - VITE_SERVER_CERTPATH=../../..${CERTS_PATH}
        volumes:
            - step:/home/step:ro
            - ./vuejs-app:/app
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - certwatch
            - php
    frontend:
        build:
            context: ./nginx
        image: proxymurder/nginx
        volumes:
            - step:/home/step:ro
            - ./vuejs-app:/app
            - ./nginx/frontend:/etc/nginx/conf.d
        networks:
            - local
            - www
        ports:
            - 3000
        depends_on:
            - certwatch
            - php
    sockjs:
        build:
            context: ./sockjs
            target: sockjs
        image: proxymurder/sockjs
        environment:
            - WS_SERVER_KEY=${DEV_SERVER_KEY}
            - WS_SERVER_CERT=${DEV_SERVER_CERT}
            - WS_PORT=5000
            - REDIS_HOST=memory
            - REDIS_PORT=6379
        volumes:
            - step:/home/step:ro
            - ./sockjs:/sockjs
        networks:
            - redis
            - local
            - www
        ports:
            - 5000
        depends_on:
            - certwatch
            - memory
    local:
        build:
            context: ./nginx
        image: proxymurder/nginx
        volumes:
            - step:/home/step:ro
            - ./nginx/local:/etc/nginx/conf.d
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - certwatch
            - ssr
            - backend
            - app
            - frontend
            - sockjs
    www:
        build:
            context: ./nginx
        image: proxymurder/nginx
        volumes:
            - step:/home/step:ro
            - ./nginx/www:/etc/nginx/conf.d
        networks:
            - www
        ports:
            - 80:80
            - 443:443
        depends_on:
            - certwatch
            - backend
            - frontend
            - sockjs
