networks:
    step:
        name: ${APP_NAME}-step-network
        driver: bridge
    redis:
        name: ${APP_NAME}-redis-network
        driver: bridge
    backend:
        name: ${APP_NAME}-backend-network
        driver: bridge
    local:
        name: ${APP_NAME}-local-network
        driver: bridge
    www:
        name: ${APP_NAME}-www-network
        driver: bridge
volumes:
    step:
        name: ${APP_NAME}-step-volume
        driver: local
    mysql:
        name: ${APP_NAME}-mysql-volume
        driver: local
    redis:
        name: ${APP_NAME}-redis-volume
        driver: local
secrets:
    password:
        file: ./ca/secrets/password
services:
    ca:
        image: proxymurder/ca:local
        environment:
            STEPCA_INIT_DNS: ca
            STEPCA_INIT_PORT: 5739
        volumes:
            - ./step/ca:/home/step
        networks:
            - step
        ports:
            - 5739
    renewer:
        image: proxymurder/renewer:local
        environment:
            COMMON_NAME: ${CERTS_NAME}
            DOMAINS: ${CERTS_DOMAINS}
            STEPPATH: ${CERTS_PATH}
            STEP_CA_URL: ${CERTS_URL}
            STEP_FINGERPRINT: ${CERTS_FINGERPRINT}
            STEP_KID: ${CERTS_KID}
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_ROOT: /home/step/root_ca.crt
        volumes:
            - step:/home/step
        secrets:
            - password
        networks:
            - step
        depends_on:
            - ca
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - backend
        ports:
            - 3306
    memory:
        image: redis:alpine
        volumes:
            - redis:/data
        networks:
            - redis
        ports:
            - 6379
    php:
        image: proxymurder/php:latest
        volumes:
            - ./laravel/src:/var/www/html
        networks:
            - backend
            - redis
        ports:
            - 9000
        depends_on:
            - db
            - memory
    nphp:
        image: proxymurder/nphp:latest
        environment:
            - VITE_SERVER_HMR=${DEV_SERVER_LARAVEL_HMR}
            - VITE_SERVER_KEY=${DEV_SERVER_KEY}
            - VITE_SERVER_CERT=${DEV_SERVER_CERT}
            - VITE_SERVER_CERTPATH=../../..${CERTS_PATH}
        volumes:
            - step:/home/step:ro
            - ./laravel/src:/var/www/html
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - renewer
            - php
    backend:
        image: proxymurder/nginx:latest
        volumes:
            - step:/home/step:ro
            - ./laravel/src:/var/www/html
            - ./nginx/backend:/etc/nginx/conf.d
        networks:
            - backend
            - local
            - www
        ports:
            - 6000
        depends_on:
            - renewer
            - php
    app:
        image: proxymurder/app:latest
        environment:
            - VITE_SERVER_KEY=${DEV_SERVER_KEY}
            - VITE_SERVER_CERT=${DEV_SERVER_CERT}
            - VITE_SERVER_CERTPATH=../../..${CERTS_PATH}
        volumes:
            - step:/home/step:ro
            - ./vue/app:/usr/share/nginx/html
        networks:
            - local
        ports:
            - 5173
        depends_on:
            - renewer
            - php
    frontend:
        image: proxymurder/nginx:latest
        volumes:
            - step:/home/step:ro
            - ./vuejs-app:/usr/share/nginx/html
            - ./nginx/frontend:/etc/nginx/conf.d
        networks:
            - local
            - www
        ports:
            - 3000
        depends_on:
            - renewer
            - php
    ws:
        image: proxymurder/websockets:latest
        environment:
            - WS_SERVER_KEY=${DEV_SERVER_KEY}
            - WS_SERVER_CERT=${DEV_SERVER_CERT}
            - WS_PORT=5000
            - REDIS_HOST=memory
            - REDIS_PORT=6379
        volumes:
            - step:/home/step:ro
            - ./ws:/home/node/ws
        networks:
            - redis
            - local
            - www
        ports:
            - 5000
        depends_on:
            - renewer
            - memory
    local:
        image: proxymurder/nginx:latest
        volumes:
            - step:/home/step:ro
            - ./nginx/local:/etc/nginx/conf.d
        networks:
            - local
        ports:
            - 80:80
            - 443:443
        depends_on:
            - renewer
            - nphp
            - backend
            - app
            - frontend
            - ws
    www:
        image: proxymurder/nginx:latest
        volumes:
            - step:/home/step:ro
            - ./nginx/www:/etc/nginx/conf.d
        networks:
            - www
        ports:
            - 80:80
            - 443:443
        depends_on:
            - renewer
            - backend
            - frontend
            - ws
