version: "3.9"
networks: 
 local:
  driver: bridge
services:
 www:
  image: nginx
  volumes:
   - ./app/dist:/usr/share/nginx/html
   - ./conf.d:/etc/nginx/conf.d
  ports:
   - 80
  networks:
   - local