#!/bin/sh
export SITECRT=/var/local/step/site.crt
export SITEKEY=/var/local/step/site.key
COMMON_NAME="${STEP_INIT_NAME:-local.site}"
function __root () {
    rm -f "${STEP_ROOT}"
    rm -f "${SITECRT}" "${SITEKEY}"
    step ca root "${STEP_ROOT}"
}
function __token () {
    local map="local test"
    if [ -n ${STEP_INIT_MAP} ]; then
        map="${map} ${STEP_INIT_MAP}"
    fi
    set -- \
    "${STEP_INIT_NAME:-local.site}" \
    --san localhost
    if [ -n "${STEP_INIT_DNS}" ]; then
        for domain in $STEP_INIT_DNS; do
            for val in $map; do
                set -- ${@} \
                --san "${domain}.${val}" \
                --san "*.${domain}.${val}"
            done
        done
    fi
    unset domain
    if [ -n "${STEP_INIT_SAN}" ]; then
        for san in $STEP_INIT_SAN; do
            set -- ${@} \
            --san "${san}"
        done
    fi
    unset san
    step ca token "${@}"
}
function __init () {
    __root
    set -- \
    --token $(__token) \
    "${COMMON_NAME}" \
    "${SITECRT}" "${SITEKEY}"
    step ca certificate "${@}"
}
__init
exec "${@}"