#!/bin/sh
export STEPPATH=$(step path)
STEP_ROOT="${STEPPATH}/root_ca.crt"
STEP_NAME="${STEP_INIT_DNS:-local}.site"
STEP_CRT="${STEPPATH}/${STEP_INIT_DNS:-local}.crt"
STEP_KEY="${STEPPATH}/${STEP_INIT_DNS:-local}.key"
function __root () {
    sleep 5
    rm -f "${STEP_ROOT}" "${STEP_CERT}" "${STEP_KEY}"
    step ca root "${STEP_ROOT}"
}
function __token () {
    local map="${STEP_INIT_MAP:-local test}"
    set -- \
    ${STEP_NAME} \
    --san localhost
    if [ -n "${STEP_INIT_DNS}" ]; then
        for domain in $STEP_INIT_DNS; do    
            for val in $map; do
                set -- ${@} \
                --san "${domain}.${val}" \
                --san "*.${domain}.${val}"
            done
        done
    fi
    if [ -n "${STEP_INIT_SAN}" ]; then
        for san in $STEP_INIT_SAN; do
            set -- ${@} \
            --san "${san}"
        done
    fi   
    step ca token "${@}"
}
function __init () {
    __root
    set -- \
    --token $(__token) \
    "${STEP_NAME}" \
    "${STEP_CRT}" \
    "${STEP_KEY}"
    step ca certificate "${@}"
}
__init
exec "${@}"