#!/bin/sh
export STEPPATH=$(step path)/renewer
export STEP_CRT="${STEPPATH}/${STEP_INIT_DNS:-local}.crt"
export STEP_KEY="${STEPPATH}/${STEP_INIT_DNS:-local}.key"
function __root () {
    local root="${STEPPATH}/root_ca.crt"
    rm -f "${root}" 
    rm -f "${STEP_CRT}" "${STEP_KEY}"
    step ca root "${root}"
}
function __token () {
    local map="local test"
    if [ -n ${STEP_INIT_MAP} ]; then
        $map="${map} ${STEP_INIT_MAP}"
    fi
    set -- \
    "${STEP_INIT_DNS:-local}.site" \
    --san "localhost"
    if [ -n "${STEP_INIT_DNS}" ]; then
        for domain in $STEP_INIT_DNS; do    
            for val in $map; do
                set -- ${@} \
                --san "${domain}.${val}" \
                --san "*.${domain}.${val}"
            done
        done
    fi
    if [ -n "${STEP_INIT_SAN}" ]; then
        for san in $STEP_INIT_SAN; do
            set -- ${@} \
            --san "${san}"
        done
    fi   
    step ca token "${@}"
}
function __init () {
    sleep 5
    __root
    set -- \
    --token $(__token) \
    "${STEP_INIT_DNS:-local}.site" \
    "${STEP_CRT}" \
    "${STEP_KEY}"
    step ca certificate "${@}"
}
__init
exec "${@}"