#!/bin/sh
export STEPPATH=$(step path)

# List of env vars required for step ca init
declare -ra REQUIRED_INIT_VARS=(STEPCA_INIT_DNS STEPCA_INIT_PORT)

# Ensure all env vars required to run step ca init are set.
function __init () {
    local missing=0
    for var in "${REQUIRED_INIT_VARS[@]}"; do
        if [ -z "${!var}" ]; then
            missing=1
        fi
    done
    if [ ${missing} = 1 ]; then
		>&2 printf "%s\n" "ca.json config file missing; please run step ca init, or provide config parameters via STEPCA_INIT_ vars"
    else
        __ca "${@}"
    fi
}

# Initialize a CA if not already initialized
function __ca () {
    local -a setup_args=(
        --name "${STEPCA_INIT_NAME:-ProxyMurder Local CA}"
        --dns "${STEPCA_INIT_DNS}"
        --provisioner "${STEPCA_INIT_PROVISIONER:-example@email.com}"
        --password-file "${STEPPATH}/password"
        --address ":${STEPCA_INIT_PORT}"
    )

    if [ -n "${STEPCA_INIT_PASSWORD}" ]; then
        printf "%s\n" "${STEPCA_INIT_PASSWORD}" > "${STEPPATH}/password"
    else
        printf "%s\n" "secret" > "${STEPPATH}/password"
    fi
    if [ -n "${STEPCA_INIT_SSH}" ]; then
        setup_args=("${setup_args[@]}" --ssh)
    fi
    step ca init "${setup_args[@]}"
}

if [ ! -f "${STEPPATH}/config/ca.json" ]; then
	__init
fi

exec "${@}"