#!/bin/sh
export STEPPATH=$(step path)

# initialize certificate authority 
function __init () {
    set -- \
    --name "${STEPCA_INIT_NAME:-ProxyMurder Local Smallstep CA}" \
    --dns "${STEPCA_INIT_DNS:-ca}" \
    --provisioner "${STEPCA_INIT_PROVISIONER:-example@email.com}" \
    --password-file "${STEPPATH}/password" \
    --address ":${STEPCA_INIT_PORT:-5739}" \
    $([[ "${STEPCA_INIT_SSH}" == "1" || "${STEPCA_INIT_SSH}" == "true" ]] && printf "%s\n" "--ssh")

    __password
    
    step ca init "${@}"
}

function __password () {
    if [ ! -f "${STEPPATH}/password" ]; then
        printf "%s\n" "secret" > "${STEPPATH}/password"
    elif [ -n "${STEPCA_INIT_PASSWORD}" ]; then
        printf "%s\n" "${STEPCA_INIT_PASSWORD}" > "${STEPPATH}/password"
    fi
}

if [ ! -f "${STEPPATH}/config/ca.json" ]; then
    __init
fi

exec "${@}"