#!/bin/sh
export STEPPATH=$(step path)

sleep 5

# get root certificate from smallstep ca
function __root () {
    rm -f "${STEPPATH}/root_ca.crt" "${STEPPATH}/site.crt" "${STEPPATH}/site.key"

    step ca root "${STEPPATH}/root_ca.crt"
}

# get token from smallstep ca
function __token () {
    set -- \
    "${STEP_INIT_NAME:-default.site}" \
    --san localhost

    local map="local test"

    if [ -n "${STEP_INIT_DNS}" ]; then
        for domain in $STEP_INIT_DNS; do    
            for val in $map; do
                set -- ${@} \
                --san "${domain}.${val}" \
                --san "*.${domain}.${val}"
            done
        done
    fi

    if [ -n "${STEP_INIT_SAN}" ]; then
        for san in $STEP_INIT_SAN; do
            set -- ${@} \
            --san "${san}"
        done
    fi
    
    step ca token "${@}"
}

# get certificates from smallstep ca
function __init () {
    __root

    set -- \
    --token $(__token) \
    "${STEP_INIT_NAME:-default.site}" \
    "${STEPPATH}/site.crt" \
    "${STEPPATH}/site.key"

    step ca certificate "${@}"
}

__init

exec "${@}"