version: '3.9'
networks:
  local:
    driver: bridge
volumes:
  mysql:
    driver: local
services:
  www:
    image: nginx
    volumes:
      - ./src:/var/www/html
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80
    depends_on:
      - php
      - db
    networks:
      - local
  php:
    build:
      context: ./src
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000
    depends_on:
      - db
    networks:
      - local
  db:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: reverse-proxy
    ports:
      - 3306
    networks:
      - local
