version: "3.9"
networks: 
 local:
  driver: bridge
services:
 www:
  image: nginx
  volumes:
   - ./src:/var/www/html
   - ./conf.d:/etc/nginx/conf.d
  ports:
   - 80
  depends_on:
   - php
  networks:
   - local
 php:
  build:
   context: ./src
  volumes:
   - ./src:/var/www/html
  ports: 
   - 9000
  networks:
   - local